#include "marine_api.hpp"

#include <algorithm>
#include <chrono>

namespace marine {
namespace {
uint64_t nowMs() { return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()); }
HttpResponse respond(const JsonValue& value, int code = 200) { HttpResponse response; response.statusCode = code; response.statusText = code == 201 ? "Created" : code == 204 ? "No Content" : code == 200 ? "OK" : "Error"; response.contentType = "application/json; charset=utf-8"; response.body = code == 204 ? "" : toJson(value); return response; }
HttpResponse failure(int code, const std::string& name, const std::string& message) { return respond(JsonValue::Object{{"error", JsonValue::Object{{"code", name}, {"message", message}}}}, code); }
const JsonValue* field(const JsonValue::Object& object, const std::string& name) { const auto it = object.find(name); return it == object.end() ? nullptr : &it->second; }
bool stringField(const JsonValue::Object& object, const std::string& name, std::string& value) { const auto item = field(object, name); if (item == nullptr || !item->isString() || item->asString().empty()) return false; value = item->asString(); return true; }
bool intField(const JsonValue::Object& object, const std::string& name, int& value) { const auto item = field(object, name); if (item == nullptr || !item->isNumber()) return false; value = static_cast<int>(item->asNumber()); return item->asNumber() == value; }
bool objectBody(const HttpRequest& request, JsonValue::Object& object, HttpResponse& invalid) { JsonValue value; std::string error; if (!parseJson(request.body, value, error) || !value.isObject()) { invalid = failure(400, "invalid_json", "请求正文必须是 JSON 对象。"); return false; } object = value.asObject(); return true; }
JsonValue bindingJson(const Binding& value) { JsonValue::Array capabilities; for (const auto& item : value.capabilities) capabilities.emplace_back(item); return JsonValue::Object{{"logicalExecutorId", value.logicalExecutorId}, {"deviceId", value.deviceId}, {"bus", value.bus}, {"address", value.address}, {"capabilities", std::move(capabilities)}, {"version", static_cast<double>(value.version)}, {"updatedAt", static_cast<double>(value.updatedAt)}, {"realControlEnabled", value.realControlEnabled}}; }
JsonValue runJson(const MarineRun& run) { JsonValue::Object result{{"id", run.id}, {"appId", run.appId}, {"status", runStatusToString(run.status)}, {"stepIndex", run.stepIndex}, {"elapsed", static_cast<double>(run.elapsedMs) / 1000}}; JsonValue::Object nodes; for (const auto& entry : run.nodes) nodes.emplace(entry.first, JsonValue::Object{{"status", nodeStatusToString(entry.second.status)}, {"elapsed", static_cast<double>(entry.second.elapsedMs) / 1000}, {"progress", entry.second.progress}, {"result", JsonValue::Object{{"metric", entry.second.result.metric}, {"value", entry.second.result.value}, {"unit", entry.second.result.unit}, {"detail", entry.second.result.detail}, {"source", entry.second.result.source}}}}); JsonValue::Array events; for (const auto& event : run.events) events.emplace_back(JsonValue::Object{{"time", static_cast<double>(event.atMs) / 1000}, {"message", event.message}, {"kind", event.kind}}); result.emplace("nodes", std::move(nodes)); result.emplace("events", std::move(events)); return result; }
std::vector<std::string> capabilitiesFor(const std::string& device) { if (device == "MOTOR-02") return {"ventilation", "speed", "status"}; if (device == "MOTOR-0E") return {"cooling", "water", "drainage", "status"}; if (device == "MOTOR-0F") return {"ventilation", "cooling", "drainage", "speed", "status"}; return {}; }
std::string addressFor(const std::string& device) { return device == "MOTOR-02" ? "0x02" : device == "MOTOR-0E" ? "0x0E" : device == "MOTOR-0F" ? "0x0F" : ""; }
bool compatible(const std::vector<std::string>& available, const std::vector<std::string>& required) { return std::all_of(required.begin(), required.end(), [&](const std::string& item) { return std::find(available.begin(), available.end(), item) != available.end(); }); }
JsonValue motorJson(const MotorTelemetry& motor) { return JsonValue::Object{{"executorId", motor.executorId}, {"name", motor.name}, {"model", motor.model}, {"address", motor.address}, {"owner", motor.owner}, {"online", motor.online}, {"running", motor.running}, {"targetRpm", motor.targetRpm}, {"actualRpm", motor.actualRpm}, {"direction", motor.direction}, {"statusWord", static_cast<double>(motor.statusWord)}, {"source", motor.source}}; }
}

MarineApi::MarineApi(MarineRepository& repository, MarineRuntime& runtime, MarineSafety& safety, std::shared_ptr<MotorAtomicService> motors) : repository_(repository), runtime_(runtime), safety_(safety), motors_(std::move(motors)) {}
HttpResponse MarineApi::handle(const HttpRequest& request) {
    const auto& path = request.path;
    if (request.method == "GET" && path == "/api/v1/health") { const auto status = safety_.status(nowMs()); return respond(JsonValue::Object{{"version", "v1"}, {"storage", "ready"}, {"sensorMode", "demo"}, {"motorMode", motors_ && !motors_->simulation() ? "real" : "simulation"}, {"actuatorControlEnabled", status.actuatorControlEnabled}, {"emergencyStopped", status.emergencyStopped}, {"locked", !status.unlocked}}); }
    if (request.method == "GET" && path == "/api/v1/marine/motors") { if (!motors_) return failure(503, "motor_service_unavailable", "电机原子服务未初始化。"); JsonValue::Array values; for (const auto& motor : motors_->list()) values.emplace_back(motorJson(motor)); return respond(values); }
    if (request.method == "POST" && (path == "/api/v1/marine/emergency-stop" || path == "/api/v1/marine/emergency-reset")) { if (!motors_) return failure(503, "motor_service_unavailable", "电机原子服务未初始化。"); JsonValue::Object body; HttpResponse invalid; if (!objectBody(request, body, invalid)) return invalid; std::string operatorName; if (!stringField(body, "operator", operatorName)) return failure(400, "validation_failed", "缺少操作员名称。"); if (path.find("reset") != std::string::npos) { motors_->resetEmergency(); safety_.resetEmergency(operatorName, nowMs()); } else { motors_->emergencyStop(); safety_.emergencyStop(operatorName, nowMs()); } const auto status = safety_.status(nowMs()); return respond(JsonValue::Object{{"actuatorControlEnabled", status.actuatorControlEnabled}, {"emergencyStopped", status.emergencyStopped}}); }
    if (request.method == "GET" && path == "/api/v1/marine/apps") { JsonValue::Array apps; for (const auto& app : repository_.listApps()) apps.push_back(applicationToJson(app)); return respond(apps); }
    if (request.method == "POST" && path == "/api/v1/marine/apps") { JsonValue body; std::string issue; Application app; if (!parseJson(request.body, body, issue) || !applicationFromJson(body, app, issue)) return failure(400, "validation_failed", issue.empty() ? "应用定义无效。" : issue); const auto saved = repository_.saveApp(app); return saved.empty() ? respond(applicationToJson(app), 201) : failure(400, "validation_failed", saved); }

    const std::string appPrefix = "/api/v1/marine/apps/";
    if (path.rfind(appPrefix, 0) == 0) { const std::string id = path.substr(appPrefix.size()); auto found = std::find_if(repository_.listApps().begin(), repository_.listApps().end(), [&](const Application& app) { return app.id == id; }); if (request.method == "GET") return found == repository_.listApps().end() ? failure(404, "not_found", "应用不存在。") : respond(applicationToJson(*found)); if (request.method == "PUT") { JsonValue body; std::string issue; Application app; if (!parseJson(request.body, body, issue) || !applicationFromJson(body, app, issue) || app.id != id) return failure(400, "validation_failed", "应用定义或 ID 无效。"); const auto saved = repository_.saveApp(app); return saved.empty() ? respond(applicationToJson(app)) : failure(400, "validation_failed", saved); } if (request.method == "DELETE") { for (const auto& run : runtime_.listRuns()) if (run.appId == id && (run.status == RunStatus::Running || run.status == RunStatus::Paused)) return failure(409, "run_active", "应用仍有运行实例。"); const auto removed = repository_.removeApp(id); return removed.empty() ? respond(JsonValue(), 204) : failure(removed == "not_found" ? 404 : 500, removed, removed == "not_found" ? "应用不存在。" : "删除应用失败。"); } }

    if (request.method == "POST" && path == "/api/v1/marine/runs") { JsonValue::Object body; HttpResponse invalid; if (!objectBody(request, body, invalid)) return invalid; std::string appId; if (!stringField(body, "appId", appId)) return failure(400, "validation_failed", "缺少 appId。"); const auto run = runtime_.createRun(appId); return run.id.empty() ? failure(404, "not_found", "应用不存在。") : respond(runJson(run), 201); }
    if (request.method == "GET" && path == "/api/v1/marine/runs") { JsonValue::Array runs; for (const auto& run : runtime_.listRuns()) runs.push_back(runJson(run)); return respond(runs); }
    const std::string runPrefix = "/api/v1/marine/runs/";
    if (path.rfind(runPrefix, 0) == 0) {
        const std::string rest = path.substr(runPrefix.size()); const auto nodesAt = rest.find("/nodes/");
        if (nodesAt != std::string::npos) { const std::string runId = rest.substr(0, nodesAt); const std::string tail = rest.substr(nodesAt + 7); const auto slash = tail.find('/'); const std::string nodeId = tail.substr(0, slash); const std::string action = slash == std::string::npos ? "" : tail.substr(slash + 1);
            if (request.method == "PATCH" && action == "motor") { JsonValue::Object body; HttpResponse invalid; if (!objectBody(request, body, invalid)) return invalid; MotorParameters parameters; std::string direction; if (!stringField(body, "executorId", parameters.executorId) || !intField(body, "speedRpm", parameters.speedRpm) || !stringField(body, "direction", direction) || !intField(body, "acceleration", parameters.acceleration) || !intField(body, "deceleration", parameters.deceleration) || parameters.speedRpm < 1 || parameters.speedRpm > 500 || parameters.acceleration < 1 || parameters.acceleration > 100 || parameters.deceleration < 1 || parameters.deceleration > 100 || (direction != "forward" && direction != "reverse")) return failure(400, "validation_failed", "电机参数不完整或超出范围。"); parameters.direction = direction == "reverse" ? MotorDirection::Reverse : MotorDirection::Forward; const auto outcome = runtime_.updateMotor(runId, nodeId, parameters); if (outcome == "not_found" || outcome == "node_not_found") return failure(404, outcome, "运行实例或节点不存在。"); if (outcome == "emergency_stopped") return failure(423, outcome, "执行器急停尚未复位。"); if (!outcome.empty()) return failure(outcome == "device_error" ? 502 : 409, outcome, "电机参数更新失败。"); return respond(runJson(*runtime_.getRun(runId))); }
            if (request.method == "POST" && action == "stop") { const auto outcome = runtime_.stopMotor(runId, nodeId); if (outcome == "not_found" || outcome == "node_not_found") return failure(404, outcome, "运行实例或节点不存在。"); if (!outcome.empty()) return failure(outcome == "device_error" ? 502 : 409, outcome, "电机停止失败。"); return respond(runJson(*runtime_.getRun(runId))); }
        }
    }
    if (path.rfind(runPrefix, 0) == 0) { const std::string rest = path.substr(runPrefix.size()); const auto slash = rest.find('/'); const std::string id = rest.substr(0, slash); const std::string action = slash == std::string::npos ? "" : rest.substr(slash + 1); if (request.method == "GET" && action.empty()) { const auto run = runtime_.getRun(id); return run ? respond(runJson(*run)) : failure(404, "not_found", "运行实例不存在。"); } if (request.method == "POST" && (action == "pause" || action == "resume" || action == "cancel")) { const auto outcome = action == "pause" ? runtime_.pauseRun(id) : action == "resume" ? runtime_.resumeRun(id) : runtime_.cancelRun(id); if (outcome == "not_found") return failure(404, outcome, "运行实例不存在。"); if (!outcome.empty()) return failure(409, outcome, "当前状态不允许该操作。"); return respond(runJson(*runtime_.getRun(id))); } }

    if (request.method == "GET" && path == "/api/v1/marine/executors") { JsonValue::Array values; for (const auto& binding : repository_.listBindings()) values.push_back(bindingJson(binding)); return respond(values); }
    const std::string executorPrefix = "/api/v1/marine/executors/";
    if (request.method == "PUT" && path.rfind(executorPrefix, 0) == 0 && path.size() > executorPrefix.size() + 8 && path.substr(path.size() - 8) == "/binding") { const std::string id = path.substr(executorPrefix.size(), path.size() - executorPrefix.size() - 8); JsonValue::Object body; HttpResponse invalid; if (!objectBody(request, body, invalid)) return invalid; std::string device, operatorName; const auto expected = field(body, "expectedVersion"); if (!stringField(body, "deviceId", device) || !stringField(body, "operator", operatorName) || expected == nullptr || !expected->isNumber() || expected->asNumber() < 0) return failure(400, "validation_failed", "绑定请求参数不完整。"); const uint64_t version = static_cast<uint64_t>(expected->asNumber()); auto current = std::find_if(repository_.listBindings().begin(), repository_.listBindings().end(), [&](const Binding& binding) { return binding.logicalExecutorId == id; }); if (current == repository_.listBindings().end()) return failure(404, "not_found", "逻辑执行器不存在。"); if (current->version != version) return failure(409, "binding_version_conflict", "设备绑定版本已变化，请重新读取。"); const auto capabilities = capabilitiesFor(device); if (capabilities.empty() || !compatible(capabilities, current->capabilities)) return failure(409, "capability_mismatch", "候选设备不具备所需能力。"); Binding updated = *current; updated.deviceId = device; updated.bus = "RS485"; updated.address = addressFor(device); updated.capabilities = capabilities; const auto saved = repository_.updateBinding(updated, version, operatorName); if (!saved.empty()) return failure(saved == "binding_version_conflict" ? 409 : 500, saved, "绑定更新失败。"); current = std::find_if(repository_.listBindings().begin(), repository_.listBindings().end(), [&](const Binding& binding) { return binding.logicalExecutorId == id; }); return respond(bindingJson(*current)); }

    if (request.method == "GET" && path == "/api/v1/safety") { const auto status = safety_.status(nowMs()); return respond(JsonValue::Object{{"actuatorControlEnabled", status.actuatorControlEnabled}, {"unlocked", status.unlocked}, {"remainingSeconds", static_cast<double>(status.remainingSeconds)}}); }
    if (request.method == "POST" && (path == "/api/v1/safety/unlock" || path == "/api/v1/safety/lock")) { JsonValue::Object body; HttpResponse invalid; if (!objectBody(request, body, invalid)) return invalid; std::string operatorName; if (!stringField(body, "operator", operatorName)) return failure(400, "validation_failed", "缺少操作员名称。"); const auto status = path == "/api/v1/safety/unlock" ? safety_.unlock(operatorName, nowMs()) : safety_.lock(operatorName, nowMs()); return respond(JsonValue::Object{{"actuatorControlEnabled", status.actuatorControlEnabled}, {"unlocked", status.unlocked}, {"remainingSeconds", static_cast<double>(status.remainingSeconds)}}); }
    return failure(404, "not_found", "接口不存在。");
}
} // namespace marine
