<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { advanceActuatorDemo, confirmActuatorSwitch, connectActuator, createActuatorDemo, disconnectActive } from '../marine/actuators'
import type { ActuatorDevice, ActuatorPhase } from '../marine/actuators'
import { marineApi } from '../marine/api'
import '../styles/hardware-decoupling.css'
const demo = ref(createActuatorDemo()); const fullscreen = ref(false); const gatewayConnected = ref(false); let timer: ReturnType<typeof setInterval> | undefined
const candidate = computed(() => demo.value.devices.find(device => device.id === demo.value.candidateId));
const statusLabels = { offline: '离线', standby: '在线待机', running: '在线运行', faulted: '设备异常' }; const phaseLabels: Record<ActuatorPhase, string> = { running: '任务运行中', protected: '保护暂停', 'awaiting-confirmation': '等待确认切换', switching: '正在切换', recovered: '任务已恢复' }; const canProtect = computed(() => ['running', 'recovered'].includes(demo.value.phase))
function protect() { demo.value = disconnectActive(demo.value) } function confirmSwitch() { demo.value = confirmActuatorSwitch(demo.value) } function connect(id: ActuatorDevice['id']) { demo.value = connectActuator(demo.value, id) } function reset() { demo.value = createActuatorDemo() }
function syncFullscreen() { fullscreen.value = Boolean(document.fullscreenElement) } async function toggleFullscreen() { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen() }
async function syncGateway() { try { gatewayConnected.value = Boolean(await marineApi.health()) } catch { gatewayConnected.value = false } }
onMounted(() => { void syncGateway(); timer = setInterval(() => { demo.value = advanceActuatorDemo(demo.value, 100) }, 100); document.addEventListener('fullscreenchange', syncFullscreen) }); onUnmounted(() => { clearInterval(timer); document.removeEventListener('fullscreenchange', syncFullscreen) })
</script>
<template>
  <div class="hardware-demo" :class="`phase-${demo.phase}`"><div class="hardware-grid-bg" aria-hidden="true"/>
    <header class="hardware-header"><RouterLink class="hardware-brand" to="/"><span class="hardware-brand-mark">⚓</span><span><strong>船舶软件定义平台</strong><small>SOFTWARE DEFINED VESSEL</small></span></RouterLink><div class="hardware-header-actions"><span class="hardware-mode"><i/> {{ gatewayConnected ? '网关接入' : '演示模式' }}</span><button @click="toggleFullscreen">⛶ {{ fullscreen ? '退出全屏' : '全屏演示' }}</button></div></header>
    <main class="hardware-main">
      <div class="screen-title"><div><span class="screen-kicker">软硬解耦 · 执行器替换</span><h1>同一任务，电机可替换</h1></div><div class="screen-status"><i/> {{ phaseLabels[demo.phase] }}<small>逻辑执行器 {{ demo.logicalExecutor.id }} 持续有效</small></div></div>
      <section class="layer-map"><div class="layer-row application-layer"><div class="layer-tag">L4</div><div class="layer-symbol">应用</div><div class="layer-copy"><strong>{{ demo.application.name }}</strong><small>{{ demo.application.id }} · 任务定义保持不变</small></div><b>0 修改</b></div><div class="flow-link"><i/><span>任务调用</span></div><div class="layer-row atomic-layer"><div class="layer-tag">L3</div><div class="layer-symbol">服务</div><div class="layer-copy"><strong>{{ demo.atomicService.name }}</strong><small>{{ demo.atomicService.id }} · 统一启停、调速、状态接口</small></div><b>0 修改</b></div><div class="flow-link"><i/><span>能力接口</span></div><div class="layer-row resource-layer"><div class="layer-tag">L2</div><div class="layer-symbol">资源</div><div class="layer-copy"><strong>{{ demo.logicalExecutor.id }} · {{ demo.logicalExecutor.name }}</strong><small>设备资源池 · 绑定关系可在运行时更新</small></div><b>抽象稳定</b></div><div class="flow-link"><i/><span>协议适配 · RS485</span></div><div class="hardware-layer-title"><div class="layer-tag">L1</div><strong>执行器硬件层</strong><small>三台电机共享同一能力接口</small></div></section>
      <section class="motor-pool"><article v-for="device in demo.devices" :key="device.id" class="motor-card" :class="[device.status, { bound: device.id === demo.logicalExecutor.boundDeviceId, candidate: device.id === demo.candidateId }]"><div class="motor-card-head"><span class="motor-status"><i/>{{ statusLabels[device.status] }}</span><span v-if="device.id === demo.logicalExecutor.boundDeviceId" class="bound-label">当前绑定</span><span v-else-if="device.id === demo.candidateId" class="candidate-label">待切换</span></div><div class="motor-visual"><span class="motor-axis"/><span class="motor-body"><i/><i/><i/></span><span class="motor-tail"/></div><h2>{{ device.name }}</h2><div class="motor-id">{{ device.id }} <em/> RS485 {{ device.address }}</div><div class="motor-readout"><div><strong>{{ device.speed || 0 }}</strong><span>RPM</span></div><div class="direction" :class="device.speed && device.status === 'running' ? 'active' : ''"><i/>{{ device.speed && device.status === 'running' ? '正转' : '待机' }}</div></div><button v-if="device.compatible && demo.phase === 'protected' && device.id !== demo.logicalExecutor.boundDeviceId" class="detect-button" @click="connect(device.id)">检测此电机</button></article></section>
      <section class="control-bar"><div class="control-caption"><span>现场演示控制</span><small>{{ demo.lastMessage }}</small></div><div class="control-actions"><button class="pull-button" :disabled="!canProtect" @click="protect"><span>拔出电机</span><small>保护当前任务</small></button><button class="switch-button" :disabled="demo.phase !== 'awaiting-confirmation'" @click="confirmSwitch"><span>确认切换</span><small>{{ candidate ? `切换至 ${candidate.address}` : '等待候选设备' }}</small></button></div><button class="reset-button" @click="reset">重置</button></section>
    </main><nav class="corner-nav"><RouterLink to="/">软件组合</RouterLink><RouterLink to="/legacy-dashboard">系统总图</RouterLink></nav><footer class="hardware-footer"><span><i/> SD VESSEL · 民用船舶软件定义演示</span><strong>应用 → 原子服务 → 设备资源池 → 执行器硬件</strong></footer>
  </div>
</template>
